export const INITIALIZE_USER = 'INITIALIZE_USER';

export const POST_USERID_INITIAL = 'POST_USERID_INITIAL';
export const POST_USERID_SUCCESS = 'POST_USERID_SUCCESS';
export const POST_USERID_FAILURE = 'POST_USERID_FAILURE';

export const POST_PROFILE_INITIAL = 'POST_PROFILE_INITIAL';
export const POST_PROFILE_SUCCESS = 'POST_PROFILE_SUCCESS';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const POST_PROFILE_FAILURE = 'POST_PROFILE_FAILURE';
